### ISSUE TITLE
好像无法正常打开？

### ISSUE THREAD

**Issue by Timearroworz** [Ukenn2112/BangumiTelegramBot#16]
是不是有问题了？？

**Comment by Ukenn2112** [comment]
正常啊什么打不开？

**Comment by Timearroworz** [comment]
> 正常啊什么打不开？
您看看…我老是这个界面
![Screenshot_2022-08-24-20-23-11-169_com.android.chrome.jpg](https://user-images.githubusercontent.com/88482265/186417354-455cbf84-b6bb-482c-a277-d4032b9ea6ba.jpg)

**Comment by Ukenn2112** [comment]
登陆需要先登陆好bgm再点绑定bangumi

**Comment by Timearroworz** [comment]
> 登陆需要先登陆好bgm再点绑定bangumi

我是这么做的呀

**Comment by Timearroworz** [comment]
> 登陆需要先登陆好bgm再点绑定bangumi
现在变成这样了，但是可以正常订阅了
![Screenshot_2022-08-24-20-37-27-158_com.android.chrome.jpg](https://user-images.githubusercontent.com/88482265/186420152-391c8043-5c01-458c-a169-58905b0d384a.jpg)

**Comment by Ukenn2112** [comment]
数据库貌似出现了点问题，我看一下

**Comment by Ukenn2112** [comment]
现在你重新start绑定看下应该好了

**Comment by Timearroworz** [comment]
> 现在你重新start绑定看下应该好了

现在完全好了，大赞👍🏻

**Comment by Ukenn2112** [comment]
好的，感谢您的使用与报告问题🎉
