### ISSUE TITLE
[疑问]

### ISSUE THREAD

**Issue by Speechless22** [Ukenn2112/BangumiTelegramBot#17]
![image](https://user-images.githubusercontent.com/61347609/204122724-14c59ae7-f913-4560-a8ae-57631ba4f439.png)
![image](https://user-images.githubusercontent.com/61347609/204122734-36afb16b-9ae1-46bd-aa96-c526d61b5b85.png)

bangumi.online订阅与追番有何区别；我能不能用BangumiBot直接控制 订阅/退订

**Comment by Ukenn2112** [comment]
BangumiBot只能进行取消订阅的操作，网页可以进行订阅和取消订阅，订阅后该番剧更新就会通过TelegramBot会推送提醒你，追番是将bgm.tv上的该番剧条目标记为在看

**Comment by Speechless22** [comment]
好的，以后的BangumiBot会更新主动订阅功能吗

**Comment by Ukenn2112** [comment]
这个不太会，BangumiBot不知道bangumi.online会上哪些番剧无法做数据的查询，目前只有用户主动找网页进行订阅

**Comment by Speechless22** [comment]
加油👍
